name: CI/CD Workflow

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check Flake8
        run: flake8 .
      - name: Check Ruff
        run: ruff check .

  push_to_docker_hub:
    needs: linting
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.316.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push project
        uses: docker/build-push-action@v2.316.1
        with:
          context: ./project
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-store-server:latest